### ISSUE TITLE
Encrypting in memory

### ISSUE THREAD

**Issue by alexrainman** [has-taiar/SQLite.Net.Cipher#1]
Why is encrypting the values in memory after saving object to database? Awesome job by the way.

**Comment by alexrainman** [comment]
I have some objects in ViewModel that i am inserting in db as user change them, but, the values in memory get encrypted too. Can you clarify? Thanks

**Comment by alexrainman** [comment]
Found a solution to this issue. I created ICloneable interface like this:

```
using System;

namespace YourNameSpace
{
    public interface ICloneable
    {
        Object Clone();
    }
}
```

Then in my object i implement Clone() method like this:

```
public Object Clone(){
    return this.MemberwiseClone ();
}
```

Before saving i Clone the object to avoid encryption in memory. Problem solved!

**Comment by has-taiar** [comment]
Hi @alexrainman, 
Thanks for reporting this issue, I can see why it is happening, I will try to resolve it soon and create a new version. 
For the time being, you could either use your workaround of Clone-ing the object before inserting to the database, or you could just Get the object from the database. Reading objects from the database will ensure that all encrypted properties are decrypted.

**Comment by alexrainman** [comment]
Hi @has-taiar i read and write from db without issues in my whole app. Only objects encrypted in memory is affecting me. My solution works by now. I was about to create a plugin like this then i found yours :+1: Thanks.
