### ISSUE TITLE
Hard-coded Salt

### ISSUE THREAD

**Issue by alexrainman** [has-taiar/SQLite.Net.Cipher#3]
The crypto-service is not randomly generating a salt that is unique as an input to the cryptographic key generation function. When generating crypto keys using salts, the salts need to be unique in order to prevent two users with from generating the same cryptographic key.

```
private const string SaltText = "MY-TEMP-SALT";
```

**Comment by alexrainman** [comment]
Is this abandonware?

**Comment by has-taiar** [comment]
fixed and pushed to nuget
